### PR TITLE
feat: Add fastembed encoder

### LINKED ISSUE #67: Add FastEmbed Encoder
FastEmbed docs: https://qdrant.github.io/fastembed/

I think this would be a simple & extremely helpful addition to the repo.

### PR DESCRIPTION
**Pull request by kdcokenny**
Closes #67 

Lmk if there are more tests that should be added or any documentation that would help.

### CODE REVIEW

**Comment by kdcokenny** [comment]
I should mention that, the only way I could get `pip install fastembed` to work was by changing the poetry version. If anyone knows any workarounds that would be great.

**Comment by jamescalam** [comment]
@kdcokenny awesome! We will review

**Review by ashraq1455 — APPROVED** [review]
Looks good to me. Thanks, @kdcokenny!

**Review by jamescalam — APPROVED** [review]
lgtm! Thanks @kdcokenny this is great

**Pull request merged**
