### PR TITLE
fix: issue #94 raise from exceptions

### PR DESCRIPTION
**Pull request by alongadot**
## Suggestion In order to resolve issue #94 

this PR uses the **raise from** idiom in order to wrap caught exceptions with additional context while preserving their original stack traces.

## Notes
The original issue required the exception in [semantic-router/semantic_router/llms/openai.py](https://github.com/aurelio-labs/semantic-router/blob/f8fcd43a7018d6216668250ff99d9acbe7f16789/semantic_router/llms/openai.py#L53) be re-raised, but this PR addresses similar occurrences of this pattern while preserving the additional context added by the new raised exceptions.

### CODE REVIEW

**Review by jamescalam — APPROVED** [review]

**Comment by jamescalam** [comment]
Looks good, thanks @alongadot — will run tests

**Comment by alongadot** [comment]
I've corrected the linting issue regarding using Conventional Commits format in the commit message. The build also failed due to a failure in uploading the Codecov report, do you have any advice on that?

**Comment by jamescalam** [comment]
@alongadot conventional commits doesn't like the length of your commit message — could you shorten it? For Codecov that's on us, I'm looking into it

**Comment by alongadot** [comment]
I've shortened the PR title to fix **Lint PR**. Please rerun, hopefully this is it :)

**Comment by alongadot** [comment]
I see **codecov/patch** failed - should I add test coverage, given no new statements were actually added?

**Comment by jamescalam** [comment]
@alongadot codecov can be difficult 😅  — we have it as optional so I am merging and we'll add coverage for those statements in the future, thanks for the PR!

**Pull request merged**
