### PR TITLE
refactor: the azure encorder file name

### PR DESCRIPTION
**Pull request by Yogendra0Sharma**
Update file name in Azure Encoder from "zure" to "azure" for improved code readability.

### CODE REVIEW

**Review by bruvduroiu — APPROVED** [review]
LGTM 🚀

**Comment by bruvduroiu** [comment]
@Yogendra0Sharma can you please change the title of the commit for this PR so that it can pass linting?

Should be as follows:

```
git reset HEAD~

# Add back your changes
git add semantic_router/encoders/

git commit -m "<commit title under 60 char>"
...
```

Thank you!

**Review by bruvduroiu — CHANGES_REQUESTED** [review]
@Yogendra0Sharma can you please change the title of the commit for this PR so that it can pass linting?

Should be as follows:

```
git reset HEAD~

# Add back your changes
git add semantic_router/encoders/

git commit -m "<commit title under 60 char>"
...
```

Thank you!

**Comment by Yogendra0Sharma** [comment]
> @Yogendra0Sharma can you please change the title of the commit for this PR so that it can pass linting?
> 
> Should be as follows:
> 
> ```
> git reset HEAD~
> 
> # Add back your changes
> git add semantic_router/encoders/
> 
> git commit -m "<commit title under 60 char>"
> ...
> ```
> 
> Thank you!

Done ! Please review.

**Comment by IZNYogendra** [comment]
@bruvduroiu Please review this PR.

**Pull request closed without merging**
