### PR TITLE
feat: Allow Pydantic V2+

### PR DESCRIPTION
**Pull request by kdcokenny**
For this, I followed this [Pydantic Migration Guide](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features) and it showed me a quick and easy way to temporarily (though probably not best practice) to allow me and others to use pydantic 2+ with semantic router.

It passes all tests so I assume it would work well while we wait for a more official pydantic v2 migration.

Lmk what you all think.

### CODE REVIEW

**Comment by kdcokenny** [comment]
This wouldn't necessarily close https://github.com/aurelio-labs/semantic-router/issues/77 but is related to it.

Also, for some reason the pytests passed but it couldn't upload it to codecov. I've never used that service so I have no idea how to fix that, but keep that in mind.

**Comment by simjak** [comment]
Thanks @kdcokenny we will take a look at both pydantic compatibility with v1 and v2, and codecov issue

**Comment by jamescalam** [comment]
@kdcokenny tests seem to be passing, but I'm seeing ValidationError when trying to run myself
image

**Review by jamescalam — CHANGES_REQUESTED** [review]
noted above

edit: testing further, may be an issue with my env, will update soon

**Review by jamescalam — APPROVED** [review]
@kdcokenny I triple checked — all looks great, thanks for the awesome PR!

**Pull request merged**
