### PR TITLE
feat: Support openai base_url

### PR DESCRIPTION
**Pull request by bdqfork**
Support setting the OpenAI client base URL to enable OpenAI-style LLM (Language Model) services.

### CODE REVIEW

**Comment by jamescalam** [comment]
@bdqfork thanks for the PR — could you fix the linting issues? We have instructions in [contributor guidelines](https://github.com/aurelio-labs/semantic-router/blob/main/CONTRIBUTING.md) (number 5), ie:

5. Ensure that All Pull Request Checks Pass There are Pull Request checks that need to be satifisfied before the changes can be merged. These appear towards the bottom of the Pull Request webpage on GitHub, and include:
  * Ensure that the Pull Request title is prepended with a [valid type](https://flank.github.io/flank/pr_titles/). E.g. `feat: My New Feature`.
    * Run linting (and fix any issues that are flagged) by:
    * Navigating to `/semantic-router`.
    * Running `make lint` to fix linting issues.
    * Running `black .` to fix black linting issues.
    * Running `ruff . --fix` to fix ruff linting issues (where possible, others may need manual changes).
    * Running `mypy .` and then fixing any of the issues that are raised.
    * Confirming the linters pass using make lint again.

Thanks!

**Comment by bdqfork** [comment]
> @bdqfork thanks for the PR — could you fix the linting issues? We have instructions in [contributor guidelines](https://github.com/aurelio-labs/semantic-router/blob/main/CONTRIBUTING.md) (number 5), ie:
> 
> 5. Ensure that All Pull Request Checks Pass There are Pull Request checks that need to be satifisfied before the changes can be merged. These appear towards the bottom of the Pull Request webpage on GitHub, and include:
> 
> * Ensure that the Pull Request title is prepended with a [valid type](https://flank.github.io/flank/pr_titles/). E.g. `feat: My New Feature`.
>   
>   * Run linting (and fix any issues that are flagged) by:
>   * Navigating to `/semantic-router`.
>   * Running `make lint` to fix linting issues.
>   * Running `black .` to fix black linting issues.
>   * Running `ruff . --fix` to fix ruff linting issues (where possible, others may need manual changes).
>   * Running `mypy .` and then fixing any of the issues that are raised.
>   * Confirming the linters pass using make lint again.
> 
> Thanks!

@jamescalam Done!

**Comment by bdqfork** [comment]
@jamescalam Are there any other questions?

**Review by jamescalam — APPROVED** [review]
lgtm, thanks @bdqfork

**Pull request merged**
