### PR TITLE
feat: Added AzureOpenAILLM

### PR DESCRIPTION
**Pull request by arashaga**
The Dynamic routing only worked with OpenAILLM now I added the AzureOpenAILLM class based following the OpenAI one now it works with Azure as well.  

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206397934940696

### CODE REVIEW

**Comment by jamescalam** [comment]
thanks for PR @arashaga — we'll review and get back to you soon

**Comment by jamescalam** [comment]
@arashaga could you add lint tweaks? (can run w/ `make lint` and `make format`) thanks!

**Comment by arashaga** [comment]
Done. had a bit of issue using the make lint on Windows but finally figure it out.

**Comment by arashaga** [comment]
I will add the tests as well.

**Comment by jamescalam** [comment]
@arashaga that'd be great! I think you will be able to take a lot of the OpenAILLM tests and just adopt them for AzureOpenAILLM here, with some small tweaks

**Comment by arashaga** [comment]
added the unit tests + make lint format. once I see the code coverage report from your end I will modify anything that might be left accordingly.

**Comment by arashaga** [comment]
now llm/zure.py getting 87% coverage on my end

**Comment by jamescalam** [comment]
Thanks @arashaga will do another review tomorrow morning and hopefully get this merged!

**Review by jamescalam — APPROVED** [review]
lgtm, thanks @arashaga !

**Pull request merged**
